name: Deploy Azure Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'functions/**'
      - '.github/workflows/functions-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r functions/requirements.txt
    
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONS_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}
        package: functions
