name: Deploy Azure Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'functions/**'
      - '.github/workflows/functions-deploy.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd functions
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run linting
      run: |
        cd functions
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'ai-tax-prototype-functions'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ./functions
